runtime: python27
api_version: latest
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|php|xml))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|php|xml))

- url: /.*
  script: login.app



